import { ScheduleJson } from "./types";

// Standard time mappings for typical university slots (12-13 slots a day)
export const SESSION_TIMES: Record<number, string> = {
    1: "08:15",
    2: "09:10",
    3: "10:15",
    4: "11:10",
    5: "13:50",
    6: "14:45",
    7: "15:40",
    8: "16:45",
    9: "17:40",
    10: "19:20",
    11: "20:15",
    12: "21:10",
    13: "22:05"
};

export const WEEK_DAYS = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
export const WEEK_DAYS_FULL = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

export const COURSE_COLORS = [
    'bg-blue-100 text-blue-800 border-blue-200',
    'bg-emerald-100 text-emerald-800 border-emerald-200',
    'bg-violet-100 text-violet-800 border-violet-200',
    'bg-amber-100 text-amber-800 border-amber-200',
    'bg-rose-100 text-rose-800 border-rose-200',
    'bg-cyan-100 text-cyan-800 border-cyan-200',
    'bg-fuchsia-100 text-fuchsia-800 border-fuchsia-200',
    'bg-lime-100 text-lime-800 border-lime-200',
];

// The raw JSON data provided by the user
export const RAW_SCHEDULE_DATA: ScheduleJson = {
    "allUnits": 27.0,
    "xkxx": [] as any, // Omitting for brevity as we use dateList
    "dateList": [
        {
            "programPlanCode": "202406120582",
            "programPlanName": "计算机科学与技术培养方案",
            "totalUnits": 27.0,
            "selectCourseList": [
                {
                    "id": {
                        "executiveEducationPlanNumber": "2025-2026-2-1",
                        "coureNumber": "105807020",
                        "coureSequenceNumber": "50",
                        "studentNumber": "2024141460445"
                    },
                    "programPlanNumber": "202406120582",
                    "courseName": "跨文化阅读",
                    "englishCourseName": "English Reading for Intercultural Communication",
                    "unit": 2.0,
                    "programPlanName": "计算机科学与技术培养方案",
                    "attendClassTeacher": "张贵芳* ",
                    "courseSelectionTime": "20251224201149",
                    "studyModeCode": "01",
                    "studyModeName": "正常",
                    "coursePropertiesCode": "001",
                    "coursePropertiesName": "必修",
                    "examTypeCode": "01",
                    "examTypeName": "考试",
                    "selectCourseStatusCode": "011",
                    "selectCourseStatusName": "抽中",
                    "courseCategoryCode": null as any,
                    "courseCategoryName": null as any,
                    "restrictedCondition": "允许修读类型 主修 \n允许年级 2024级 \n允许年级 2023级 \n",
                    "zkxh": null as any,
                    "fsktms": null as any,
                    "sfczfskt": null as any,
                    "xkzy": null as any,
                    "cxfsdm": "0",
                    "zkch": null as any,
                    "xtbz": "计算选课优先级：84110175_202.115.47.139_2025123010225520251230102517抽中",
                    "xkkzh": "3",
                    "timeAndPlaceList": [
                        {
                            "id": "2025-2026-2-110580702050202414146044511111111111111110000000013",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "105807020",
                            "coureSequenceNumber": "50",
                            "studentNumber": "2024141460445",
                            "classWeek": "111111111111111100000000",
                            "classDay": 1,
                            "classSessions": 3,
                            "campusName": "江安",
                            "teachingBuildingName": "综合楼B座",
                            "classroomName": "B603",
                            "weekDescription": "1-16周",
                            "continuingSession": 2,
                            "coursePropertiesName": "必修",
                            "coureName": "跨文化阅读",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        }
                    ],
                    "flag": null as any,
                    "dgFlag": "（无）",
                    "ywdgFlag": "（无）",
                    "rlFlag": "20032200,张贵芳（无）",
                    "xkkzm": "英语模块课程"
                },
                {
                    "id": {
                        "executiveEducationPlanNumber": "2025-2026-2-1",
                        "coureNumber": "107118000",
                        "coureSequenceNumber": "17",
                        "studentNumber": "2024141460445"
                    },
                    "programPlanNumber": "202406120582",
                    "courseName": "形势与政策-4",
                    "englishCourseName": "Situation and Policy-4",
                    "unit": 0.0,
                    "programPlanName": "计算机科学与技术培养方案",
                    "attendClassTeacher": "耿天玉* ",
                    "courseSelectionTime": "20251217111035",
                    "studyModeCode": "01",
                    "studyModeName": "正常",
                    "coursePropertiesCode": "001",
                    "coursePropertiesName": "必修",
                    "examTypeCode": "01",
                    "examTypeName": "考试",
                    "selectCourseStatusCode": "016",
                    "selectCourseStatusName": "置入",
                    "courseCategoryCode": "0",
                    "courseCategoryName": "国家统一课",
                    "restrictedCondition": "允许院系专业： 数学学院\n计算机学院（软件学院、智能科学与技术学院）\n允许修读类型 主修 \n允许年级 2022级 \n允许年级 2024级 \n",
                    "zkxh": null,
                    "fsktms": null,
                    "sfczfskt": null,
                    "xkzy": null,
                    "cxfsdm": null,
                    "zkch": null,
                    "xtbz": null,
                    "xkkzh": null,
                    "timeAndPlaceList": [
                        {
                            "id": "2025-2026-2-110711800017202414146044510101010000000000000000055",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "107118000",
                            "coureSequenceNumber": "17",
                            "studentNumber": "2024141460445",
                            "classWeek": "101010100000000000000000",
                            "classDay": 5,
                            "classSessions": 5,
                            "campusName": "江安",
                            "teachingBuildingName": "综合楼C座",
                            "classroomName": "C504",
                            "weekDescription": "1-7周单周",
                            "continuingSession": 2,
                            "coursePropertiesName": "必修",
                            "coureName": "形势与政策-4",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        }
                    ],
                    "flag": null,
                    "dgFlag": "（无）",
                    "ywdgFlag": "（无）",
                    "rlFlag": "20182065,耿天玉（无）",
                    "xkkzm": null
                },
                {
                    "id": {
                        "executiveEducationPlanNumber": "2025-2026-2-1",
                        "coureNumber": "107446030",
                        "coureSequenceNumber": "57",
                        "studentNumber": "2024141460445"
                    },
                    "programPlanNumber": "202406120582",
                    "courseName": "毛泽东思想和中国特色社会主义理论体系概论",
                    "englishCourseName": "The outline of Mao Tse-tung thought and socialist theoretical system with Chinese characteristics ",
                    "unit": 3.0,
                    "programPlanName": "计算机科学与技术培养方案",
                    "attendClassTeacher": "祝林林* ",
                    "courseSelectionTime": "20260106095017",
                    "studyModeCode": "01",
                    "studyModeName": "正常",
                    "coursePropertiesCode": "001",
                    "coursePropertiesName": "必修",
                    "examTypeCode": "01",
                    "examTypeName": "考试",
                    "selectCourseStatusCode": "001",
                    "selectCourseStatusName": "选中",
                    "courseCategoryCode": "0",
                    "courseCategoryName": "国家统一课",
                    "restrictedCondition": "允许院系专业： 机械工程学院\r\n电气工程学院\r\n建筑与环境学院\r\n水利水电学院\r\n计算机学院（软件学院、智能科学与技术学院）\r\n网络空间安全学院\r\n电子信息学院\r\n匹兹堡学院\r\n",
                    "zkxh": null,
                    "fsktms": null,
                    "sfczfskt": null,
                    "xkzy": null,
                    "cxfsdm": "0",
                    "zkch": null,
                    "xtbz": null,
                    "xkkzh": null,
                    "timeAndPlaceList": [
                        {
                            "id": "2025-2026-2-1107446030572024141460445111111111111111100000000410",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "107446030",
                            "coureSequenceNumber": "57",
                            "studentNumber": "2024141460445",
                            "classWeek": "111111111111111100000000",
                            "classDay": 4,
                            "classSessions": 10,
                            "campusName": "江安",
                            "teachingBuildingName": "一教B座",
                            "classroomName": "B502",
                            "weekDescription": "1-16周",
                            "continuingSession": 3,
                            "coursePropertiesName": "必修",
                            "coureName": "毛泽东思想和中国特色社会主义理论体系概论",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        }
                    ],
                    "flag": null,
                    "dgFlag": "（无）",
                    "ywdgFlag": "（无）",
                    "rlFlag": "20232092,祝林林（无）",
                    "xkkzm": null
                },
                {
                    "id": {
                        "executiveEducationPlanNumber": "2025-2026-2-1",
                        "coureNumber": "107447030",
                        "coureSequenceNumber": "58",
                        "studentNumber": "2024141460445"
                    },
                    "programPlanNumber": "202406120582",
                    "courseName": "习近平新时代中国特色社会主义思想概论",
                    "englishCourseName": "Introduction to Xi Jinping Thought on Socialism with Chinese Characteristics for a New Era",
                    "unit": 3.0,
                    "programPlanName": "计算机科学与技术培养方案",
                    "attendClassTeacher": "邓睦军* ",
                    "courseSelectionTime": "20251217111035",
                    "studyModeCode": "01",
                    "studyModeName": "正常",
                    "coursePropertiesCode": "001",
                    "coursePropertiesName": "必修",
                    "examTypeCode": null,
                    "examTypeName": null,
                    "selectCourseStatusCode": "016",
                    "selectCourseStatusName": "置入",
                    "courseCategoryCode": "0",
                    "courseCategoryName": "国家统一课",
                    "restrictedCondition": "允许院系专业： 机械工程学院\r\n电气工程学院\r\n建筑与环境学院\r\n水利水电学院\r\n计算机学院（软件学院、智能科学与技术学院）\r\n网络空间安全学院\r\n电子信息学院\r\n匹兹堡学院\r\n",
                    "zkxh": null,
                    "fsktms": null,
                    "sfczfskt": null,
                    "xkzy": null,
                    "cxfsdm": null,
                    "zkch": null,
                    "xtbz": null,
                    "xkkzh": null,
                    "timeAndPlaceList": [
                        {
                            "id": "2025-2026-2-110744703058202414146044511111111111111110000000045",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "107447030",
                            "coureSequenceNumber": "58",
                            "studentNumber": "2024141460445",
                            "classWeek": "111111111111111100000000",
                            "classDay": 4,
                            "classSessions": 5,
                            "campusName": "江安",
                            "teachingBuildingName": "一教B座",
                            "classroomName": "B303",
                            "weekDescription": "1-16周",
                            "continuingSession": 3,
                            "coursePropertiesName": "必修",
                            "coureName": "习近平新时代中国特色社会主义思想概论",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        }
                    ],
                    "flag": null,
                    "dgFlag": "（无）",
                    "ywdgFlag": "（无）",
                    "rlFlag": "20202281,邓睦军（无）",
                    "xkkzm": null
                },
                {
                    "id": {
                        "executiveEducationPlanNumber": "2025-2026-2-1",
                        "coureNumber": "304009010",
                        "coureSequenceNumber": "05",
                        "studentNumber": "2024141460445"
                    },
                    "programPlanNumber": "202406120582",
                    "courseName": "操作系统课程设计",
                    "englishCourseName": "Curriculum Design of Operating System",
                    "unit": 1.0,
                    "programPlanName": "计算机科学与技术培养方案",
                    "attendClassTeacher": "左劼* ",
                    "courseSelectionTime": "20251217111035",
                    "studyModeCode": "01",
                    "studyModeName": "正常",
                    "coursePropertiesCode": "001",
                    "coursePropertiesName": "必修",
                    "examTypeCode": "02",
                    "examTypeName": "考查",
                    "selectCourseStatusCode": "016",
                    "selectCourseStatusName": "置入",
                    "courseCategoryCode": null,
                    "courseCategoryName": null,
                    "restrictedCondition": "允许院系专业 计算机学院\n计算机学院（软件学院、智能科学与技术学院）\n数学学院\n",
                    "zkxh": null,
                    "fsktms": null,
                    "sfczfskt": null,
                    "xkzy": null,
                    "cxfsdm": null,
                    "zkch": null,
                    "xtbz": null,
                    "xkkzh": null,
                    "timeAndPlaceList": [
                        {
                            "id": "2025-2026-2-130400901005202414146044500000111111111100000000018",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "304009010",
                            "coureSequenceNumber": "05",
                            "studentNumber": "2024141460445",
                            "classWeek": "000001111111111000000000",
                            "classDay": 1,
                            "classSessions": 8,
                            "campusName": "江安",
                            "teachingBuildingName": "实验室",
                            "classroomName": "二基楼B301",
                            "weekDescription": "6-15周",
                            "continuingSession": 2,
                            "coursePropertiesName": "必修",
                            "coureName": "操作系统课程设计",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        }
                    ],
                    "flag": null,
                    "dgFlag": "（无）",
                    "ywdgFlag": "（无）",
                    "rlFlag": "20052004,左劼（无）",
                    "xkkzm": null
                },
                {
                    "id": {
                        "executiveEducationPlanNumber": "2025-2026-2-1",
                        "coureNumber": "304019030",
                        "coureSequenceNumber": "05",
                        "studentNumber": "2024141460445"
                    },
                    "programPlanNumber": "202406120582",
                    "courseName": "操作系统原理",
                    "englishCourseName": "Operating System",
                    "unit": 3.0,
                    "programPlanName": "计算机科学与技术培养方案",
                    "attendClassTeacher": "左劼* ",
                    "courseSelectionTime": "20251217111035",
                    "studyModeCode": "01",
                    "studyModeName": "正常",
                    "coursePropertiesCode": "001",
                    "coursePropertiesName": "必修",
                    "examTypeCode": null,
                    "examTypeName": null,
                    "selectCourseStatusCode": "016",
                    "selectCourseStatusName": "置入",
                    "courseCategoryCode": null,
                    "courseCategoryName": null,
                    "restrictedCondition": "允许院系专业 计算机学院\n计算机学院（软件学院、智能科学与技术学院）\n数学学院\n",
                    "zkxh": null,
                    "fsktms": null,
                    "sfczfskt": null,
                    "xkzy": null,
                    "cxfsdm": null,
                    "zkch": null,
                    "xtbz": null,
                    "xkkzh": null,
                    "timeAndPlaceList": [
                        {
                            "id": "2025-2026-2-130401903005202414146044511111111111111110000000015",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "304019030",
                            "coureSequenceNumber": "05",
                            "studentNumber": "2024141460445",
                            "classWeek": "111111111111111100000000",
                            "classDay": 1,
                            "classSessions": 5,
                            "campusName": "江安",
                            "teachingBuildingName": "一教B座",
                            "classroomName": "B501",
                            "weekDescription": "1-16周",
                            "continuingSession": 3,
                            "coursePropertiesName": "必修",
                            "coureName": "操作系统原理",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        }
                    ],
                    "flag": null,
                    "dgFlag": "（无）",
                    "ywdgFlag": "（无）",
                    "rlFlag": "20052004,左劼（无）",
                    "xkkzm": null
                },
                {
                    "id": {
                        "executiveEducationPlanNumber": "2025-2026-2-1",
                        "coureNumber": "304036030",
                        "coureSequenceNumber": "05",
                        "studentNumber": "2024141460445"
                    },
                    "programPlanNumber": "202406120582",
                    "courseName": "计算机组成原理",
                    "englishCourseName": "Principles of Computer Organization",
                    "unit": 3.0,
                    "programPlanName": "计算机科学与技术培养方案",
                    "attendClassTeacher": "应三丛* ",
                    "courseSelectionTime": "20251217111035",
                    "studyModeCode": "01",
                    "studyModeName": "正常",
                    "coursePropertiesCode": "001",
                    "coursePropertiesName": "必修",
                    "examTypeCode": "01",
                    "examTypeName": "考试",
                    "selectCourseStatusCode": "016",
                    "selectCourseStatusName": "置入",
                    "courseCategoryCode": null,
                    "courseCategoryName": null,
                    "restrictedCondition": "允许院系专业 计算机学院\n计算机学院（软件学院、智能科学与技术学院）\n",
                    "zkxh": null,
                    "fsktms": null,
                    "sfczfskt": null,
                    "xkzy": null,
                    "cxfsdm": null,
                    "zkch": null,
                    "xtbz": null,
                    "xkkzh": null,
                    "timeAndPlaceList": [
                        {
                            "id": "2025-2026-2-130403603005202414146044511111111111111110000000035",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "304036030",
                            "coureSequenceNumber": "05",
                            "studentNumber": "2024141460445",
                            "classWeek": "111111111111111100000000",
                            "classDay": 3,
                            "classSessions": 5,
                            "campusName": "江安",
                            "teachingBuildingName": "一教A座",
                            "classroomName": "A318",
                            "weekDescription": "1-16周",
                            "continuingSession": 3,
                            "coursePropertiesName": "必修",
                            "coureName": "计算机组成原理",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        }
                    ],
                    "flag": null,
                    "dgFlag": "（无）",
                    "ywdgFlag": "（无）",
                    "rlFlag": "20011069,应三丛（无）",
                    "xkkzm": null
                },
                {
                    "id": {
                        "executiveEducationPlanNumber": "2025-2026-2-1",
                        "coureNumber": "304037010",
                        "coureSequenceNumber": "05",
                        "studentNumber": "2024141460445"
                    },
                    "programPlanNumber": "202406120582",
                    "courseName": "计算机组成原理实验",
                    "englishCourseName": "Experiment in Computer Organization Theory",
                    "unit": 1.0,
                    "programPlanName": "计算机科学与技术培养方案",
                    "attendClassTeacher": "应三丛* ",
                    "courseSelectionTime": "20251217111036",
                    "studyModeCode": "01",
                    "studyModeName": "正常",
                    "coursePropertiesCode": "001",
                    "coursePropertiesName": "必修",
                    "examTypeCode": "02",
                    "examTypeName": "考查",
                    "selectCourseStatusCode": "016",
                    "selectCourseStatusName": "置入",
                    "courseCategoryCode": null,
                    "courseCategoryName": null,
                    "restrictedCondition": "允许院系专业 计算机学院\n计算机学院（软件学院、智能科学与技术学院）\n",
                    "zkxh": null,
                    "fsktms": null,
                    "sfczfskt": null,
                    "xkzy": null,
                    "cxfsdm": null,
                    "zkch": null,
                    "xtbz": null,
                    "xkkzh": null,
                    "timeAndPlaceList": [
                        {
                            "id": "2025-2026-2-130403701005202414146044500000000001111100000000051",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "304037010",
                            "coureSequenceNumber": "05",
                            "studentNumber": "2024141460445",
                            "classWeek": "000000000011111000000000",
                            "classDay": 5,
                            "classSessions": 1,
                            "campusName": "江安",
                            "teachingBuildingName": "实验室",
                            "classroomName": "二基楼B310B",
                            "weekDescription": "11-15周",
                            "continuingSession": 4,
                            "coursePropertiesName": "必修",
                            "coureName": "计算机组成原理实验",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        }
                    ],
                    "flag": null,
                    "dgFlag": "（无）",
                    "ywdgFlag": "（无）",
                    "rlFlag": "20011069,应三丛（无）",
                    "xkkzm": null
                },
                {
                    "id": {
                        "executiveEducationPlanNumber": "2025-2026-2-1",
                        "coureNumber": "304043020",
                        "coureSequenceNumber": "01",
                        "studentNumber": "2024141460445"
                    },
                    "programPlanNumber": "202406120582",
                    "courseName": "软件开发环境与工具",
                    "englishCourseName": "Software Development Environment & Tools",
                    "unit": 2.0,
                    "programPlanName": "计算机科学与技术培养方案",
                    "attendClassTeacher": "黄戈* ",
                    "courseSelectionTime": "20260106103437",
                    "studyModeCode": "01",
                    "studyModeName": "正常",
                    "coursePropertiesCode": "002",
                    "coursePropertiesName": "选修",
                    "examTypeCode": "02",
                    "examTypeName": "考查",
                    "selectCourseStatusCode": "001",
                    "selectCourseStatusName": "选中",
                    "courseCategoryCode": null,
                    "courseCategoryName": null,
                    "restrictedCondition": "允许院系专业 计算机学院\n计算机学院（软件学院、智能科学与技术学院）\n",
                    "zkxh": null,
                    "fsktms": null,
                    "sfczfskt": null,
                    "xkzy": null,
                    "cxfsdm": "0",
                    "zkch": null,
                    "xtbz": null,
                    "xkkzh": null,
                    "timeAndPlaceList": [
                        {
                            "id": "2025-2026-2-130404302001202414146044511111111111111110000000043",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "304043020",
                            "coureSequenceNumber": "01",
                            "studentNumber": "2024141460445",
                            "classWeek": "111111111111111100000000",
                            "classDay": 4,
                            "classSessions": 3,
                            "campusName": "江安",
                            "teachingBuildingName": "实验室",
                            "classroomName": "二基楼B201",
                            "weekDescription": "1-16周",
                            "continuingSession": 2,
                            "coursePropertiesName": "选修",
                            "coureName": "软件开发环境与工具",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        }
                    ],
                    "flag": null,
                    "dgFlag": "（无）",
                    "ywdgFlag": "（无）",
                    "rlFlag": "20042115,黄戈（无）",
                    "xkkzm": null
                },
                {
                    "id": {
                        "executiveEducationPlanNumber": "2025-2026-2-1",
                        "coureNumber": "304055030",
                        "coureSequenceNumber": "01",
                        "studentNumber": "2024141460445"
                    },
                    "programPlanNumber": "202406120582",
                    "courseName": "网络工程",
                    "englishCourseName": "Network Engineering",
                    "unit": 3.0,
                    "programPlanName": "计算机科学与技术培养方案",
                    "attendClassTeacher": "傅静涛* ",
                    "courseSelectionTime": "20251224203801",
                    "studyModeCode": "01",
                    "studyModeName": "正常",
                    "coursePropertiesCode": "002",
                    "coursePropertiesName": "选修",
                    "examTypeCode": "02",
                    "examTypeName": "考查",
                    "selectCourseStatusCode": "001",
                    "selectCourseStatusName": "选中",
                    "courseCategoryCode": null,
                    "courseCategoryName": null,
                    "restrictedCondition": "允许院系专业 计算机学院\n计算机学院（软件学院、智能科学与技术学院）\n",
                    "zkxh": null,
                    "fsktms": null,
                    "sfczfskt": null,
                    "xkzy": null,
                    "cxfsdm": "0",
                    "zkch": null,
                    "xtbz": "计算选课优先级：84110175_202.115.47.139_20251230103057抽签：84110175_202.115.47.139_20251230103101优先级高",
                    "xkkzh": null,
                    "timeAndPlaceList": [
                        {
                            "id": "2025-2026-2-130405503001202414146044511111111111111110000000025",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "304055030",
                            "coureSequenceNumber": "01",
                            "studentNumber": "2024141460445",
                            "classWeek": "111111111111111100000000",
                            "classDay": 2,
                            "classSessions": 5,
                            "campusName": "江安",
                            "teachingBuildingName": "一教A座",
                            "classroomName": "A106",
                            "weekDescription": "1-16周",
                            "continuingSession": 3,
                            "coursePropertiesName": "选修",
                            "coureName": "网络工程",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        }
                    ],
                    "flag": null,
                    "dgFlag": "（无）",
                    "ywdgFlag": "（无）",
                    "rlFlag": "81076980,傅静涛（无）",
                    "xkkzm": null
                },
                {
                    "id": {
                        "executiveEducationPlanNumber": "2025-2026-2-1",
                        "coureNumber": "304056010",
                        "coureSequenceNumber": "01",
                        "studentNumber": "2024141460445"
                    },
                    "programPlanNumber": "202406120582",
                    "courseName": "网络工程课程设计",
                    "englishCourseName": "Course Design of Network Engineering",
                    "unit": 1.0,
                    "programPlanName": "计算机科学与技术培养方案",
                    "attendClassTeacher": "傅静涛* ",
                    "courseSelectionTime": "20251224203802",
                    "studyModeCode": "01",
                    "studyModeName": "正常",
                    "coursePropertiesCode": "002",
                    "coursePropertiesName": "选修",
                    "examTypeCode": "02",
                    "examTypeName": "考查",
                    "selectCourseStatusCode": "001",
                    "selectCourseStatusName": "选中",
                    "courseCategoryCode": null,
                    "courseCategoryName": null,
                    "restrictedCondition": "允许院系专业 计算机学院\n计算机学院（软件学院、智能科学与技术学院）\n",
                    "zkxh": null,
                    "fsktms": null,
                    "sfczfskt": null,
                    "xkzy": null,
                    "cxfsdm": "0",
                    "zkch": null,
                    "xtbz": "计算选课优先级：84110175_202.115.47.139_20251230103057抽签：84110175_202.115.47.139_20251230103101优先级高",
                    "xkkzh": null,
                    "timeAndPlaceList": [
                        {
                            "id": "2025-2026-2-130405601001202414146044500000111111111100000000023",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "304056010",
                            "coureSequenceNumber": "01",
                            "studentNumber": "2024141460445",
                            "classWeek": "000001111111111000000000",
                            "classDay": 2,
                            "classSessions": 3,
                            "campusName": "江安",
                            "teachingBuildingName": "实验室",
                            "classroomName": "二基楼B310A",
                            "weekDescription": "6-15周",
                            "continuingSession": 2,
                            "coursePropertiesName": "选修",
                            "coureName": "网络工程课程设计",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        }
                    ],
                    "flag": null,
                    "dgFlag": "（无）",
                    "ywdgFlag": "（无）",
                    "rlFlag": "81076980,傅静涛（无）",
                    "xkkzm": null
                },
                {
                    "id": {
                        "executiveEducationPlanNumber": "2025-2026-2-1",
                        "coureNumber": "313107020",
                        "coureSequenceNumber": "02",
                        "studentNumber": "2024141460445"
                    },
                    "programPlanNumber": "202406120582",
                    "courseName": "问天寻梦：航天科技与星际探索",
                    "englishCourseName": "Journey to Dream：Astronautical Science and Interstellar Exploration\r\n",
                    "unit": 2.0,
                    "programPlanName": "计算机科学与技术培养方案",
                    "attendClassTeacher": "周青华* 刘学文 孙铮 陶军 郝松华 周广武 宁召柯 ",
                    "courseSelectionTime": "20251224210427",
                    "studyModeCode": "01",
                    "studyModeName": "正常",
                    "coursePropertiesCode": "003",
                    "coursePropertiesName": "任选",
                    "examTypeCode": null,
                    "examTypeName": null,
                    "selectCourseStatusCode": "011",
                    "selectCourseStatusName": "抽中",
                    "courseCategoryCode": "701",
                    "courseCategoryName": "通识模块-自然与科技",
                    "restrictedCondition": null,
                    "zkxh": null,
                    "fsktms": null,
                    "sfczfskt": null,
                    "xkzy": null,
                    "cxfsdm": "0",
                    "zkch": null,
                    "xtbz": "计算选课优先级：84110175_202.115.47.139_2025123010342020251230103425抽中",
                    "xkkzh": null,
                    "timeAndPlaceList": [
                        {
                            "id": "2025-2026-2-1313107020022024141460445111000000000000000000000110",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "313107020",
                            "coureSequenceNumber": "02",
                            "studentNumber": "2024141460445",
                            "classWeek": "111000000000000000000000",
                            "classDay": 1,
                            "classSessions": 10,
                            "campusName": "江安",
                            "teachingBuildingName": "一教B座",
                            "classroomName": "B202",
                            "weekDescription": "1-3周",
                            "continuingSession": 2,
                            "coursePropertiesName": "任选",
                            "coureName": "问天寻梦：航天科技与星际探索",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        },
                        {
                            "id": "2025-2026-2-1313107020022024141460445000111000000000000000000110",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "313107020",
                            "coureSequenceNumber": "02",
                            "studentNumber": "2024141460445",
                            "classWeek": "000111000000000000000000",
                            "classDay": 1,
                            "classSessions": 10,
                            "campusName": "江安",
                            "teachingBuildingName": "一教B座",
                            "classroomName": "B202",
                            "weekDescription": "4-6周",
                            "continuingSession": 2,
                            "coursePropertiesName": "任选",
                            "coureName": "问天寻梦：航天科技与星际探索",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        },
                        {
                            "id": "2025-2026-2-1313107020022024141460445000000110000000000000000110",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "313107020",
                            "coureSequenceNumber": "02",
                            "studentNumber": "2024141460445",
                            "classWeek": "000000110000000000000000",
                            "classDay": 1,
                            "classSessions": 10,
                            "campusName": "江安",
                            "teachingBuildingName": "一教B座",
                            "classroomName": "B202",
                            "weekDescription": "7-8周",
                            "continuingSession": 2,
                            "coursePropertiesName": "任选",
                            "coureName": "问天寻梦：航天科技与星际探索",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        },
                        {
                            "id": "2025-2026-2-1313107020022024141460445000000001100000000000000110",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "313107020",
                            "coureSequenceNumber": "02",
                            "studentNumber": "2024141460445",
                            "classWeek": "000000001100000000000000",
                            "classDay": 1,
                            "classSessions": 10,
                            "campusName": "江安",
                            "teachingBuildingName": "一教B座",
                            "classroomName": "B202",
                            "weekDescription": "9-10周",
                            "continuingSession": 2,
                            "coursePropertiesName": "任选",
                            "coureName": "问天寻梦：航天科技与星际探索",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        },
                        {
                            "id": "2025-2026-2-1313107020022024141460445000000000011000000000000110",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "313107020",
                            "coureSequenceNumber": "02",
                            "studentNumber": "2024141460445",
                            "classWeek": "000000000011000000000000",
                            "classDay": 1,
                            "classSessions": 10,
                            "campusName": "江安",
                            "teachingBuildingName": "一教B座",
                            "classroomName": "B202",
                            "weekDescription": "11-12周",
                            "continuingSession": 2,
                            "coursePropertiesName": "任选",
                            "coureName": "问天寻梦：航天科技与星际探索",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        },
                        {
                            "id": "2025-2026-2-1313107020022024141460445000000000000100000000000110",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "313107020",
                            "coureSequenceNumber": "02",
                            "studentNumber": "2024141460445",
                            "classWeek": "000000000000100000000000",
                            "classDay": 1,
                            "classSessions": 10,
                            "campusName": "江安",
                            "teachingBuildingName": "一教B座",
                            "classroomName": "B202",
                            "weekDescription": "第13周",
                            "continuingSession": 2,
                            "coursePropertiesName": "任选",
                            "coureName": "问天寻梦：航天科技与星际探索",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        },
                        {
                            "id": "2025-2026-2-1313107020022024141460445000000000000011100000000110",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "313107020",
                            "coureSequenceNumber": "02",
                            "studentNumber": "2024141460445",
                            "classWeek": "000000000000011100000000",
                            "classDay": 1,
                            "classSessions": 10,
                            "campusName": "江安",
                            "teachingBuildingName": "一教B座",
                            "classroomName": "B202",
                            "weekDescription": "14-16周",
                            "continuingSession": 2,
                            "coursePropertiesName": "任选",
                            "coureName": "问天寻梦：航天科技与星际探索",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        }
                    ],
                    "flag": null,
                    "dgFlag": "（无）",
                    "ywdgFlag": "（无）",
                    "rlFlag": "20092068,刘学文（无）|20122090,孙铮（无）|20132072,周广武（无）|20142036,周青华（无）|20202044,郝松华（无）|20202311,宁召柯（无）|84100027,陶军（无）",
                    "xkkzm": null
                },
                {
                    "id": {
                        "executiveEducationPlanNumber": "2025-2026-2-1",
                        "coureNumber": "314073020",
                        "coureSequenceNumber": "01",
                        "studentNumber": "2024141460445"
                    },
                    "programPlanNumber": "202406120582",
                    "courseName": "从碳基到硅基：信息技术与文明再造",
                    "englishCourseName": "Carbon-based to Silicon-based: Information Technology and Civilizations Reconstitution",
                    "unit": 2.0,
                    "programPlanName": "计算机科学与技术培养方案",
                    "attendClassTeacher": "赵辉* ",
                    "courseSelectionTime": "20251224205249",
                    "studyModeCode": "01",
                    "studyModeName": "正常",
                    "coursePropertiesCode": "003",
                    "coursePropertiesName": "任选",
                    "examTypeCode": "02",
                    "examTypeName": "考查",
                    "selectCourseStatusCode": "011",
                    "selectCourseStatusName": "抽中",
                    "courseCategoryCode": "703",
                    "courseCategoryName": "通识模块-信息与交叉",
                    "restrictedCondition": "允许修读类型 主修 \r\n",
                    "zkxh": null,
                    "fsktms": null,
                    "sfczfskt": null,
                    "xkzy": null,
                    "cxfsdm": "0",
                    "zkch": null,
                    "xtbz": "计算选课优先级：84110175_202.115.47.139_2025123010343720251230103440抽中",
                    "xkkzh": null,
                    "timeAndPlaceList": [
                        {
                            "id": "2025-2026-2-131407302001202414146044511111111111111110000000028",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "314073020",
                            "coureSequenceNumber": "01",
                            "studentNumber": "2024141460445",
                            "classWeek": "111111111111111100000000",
                            "classDay": 2,
                            "classSessions": 8,
                            "campusName": "江安",
                            "teachingBuildingName": "一教A座",
                            "classroomName": "A320",
                            "weekDescription": "1-16周",
                            "continuingSession": 2,
                            "coursePropertiesName": "任选",
                            "coureName": "从碳基到硅基：信息技术与文明再造",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        }
                    ],
                    "flag": null,
                    "dgFlag": "（无）",
                    "ywdgFlag": "（无）",
                    "rlFlag": "20032153,赵辉（无）",
                    "xkkzm": null
                },
                {
                    "id": {
                        "executiveEducationPlanNumber": "2025-2026-2-1",
                        "coureNumber": "888007010A43",
                        "coureSequenceNumber": "07",
                        "studentNumber": "2024141460445"
                    },
                    "programPlanNumber": "202406120582",
                    "courseName": "体育-4太极拳",
                    "englishCourseName": "Physical Education-4",
                    "unit": 1.0,
                    "programPlanName": "计算机科学与技术培养方案",
                    "attendClassTeacher": "杜昊滢* ",
                    "courseSelectionTime": "20251224203957",
                    "studyModeCode": "01",
                    "studyModeName": "正常",
                    "coursePropertiesCode": "001",
                    "coursePropertiesName": "必修",
                    "examTypeCode": "02",
                    "examTypeName": "考查",
                    "selectCourseStatusCode": "011",
                    "selectCourseStatusName": "抽中",
                    "courseCategoryCode": "0",
                    "courseCategoryName": "国家统一课",
                    "restrictedCondition": null,
                    "zkxh": null,
                    "fsktms": null,
                    "sfczfskt": null,
                    "xkzy": null,
                    "cxfsdm": "0",
                    "zkch": "888007010",
                    "xtbz": "计算选课优先级：84100125_202.115.47.139_2025123010362020251230103631抽中",
                    "xkkzh": "6",
                    "timeAndPlaceList": [
                        {
                            "id": "2025-2026-2-1888007010A4307202414146044511111111111111110000000033",
                            "executiveEducationPlanNumber": "2025-2026-2-1",
                            "coureNumber": "888007010A43",
                            "coureSequenceNumber": "07",
                            "studentNumber": "2024141460445",
                            "classWeek": "111111111111111100000000",
                            "classDay": 3,
                            "classSessions": 3,
                            "campusName": "江安",
                            "teachingBuildingName": "体育场",
                            "classroomName": "不高山小广场",
                            "weekDescription": "1-16周",
                            "continuingSession": 2,
                            "coursePropertiesName": "必修",
                            "coureName": "体育-4太极拳",
                            "courseTeacher": null,
                            "sksj": null,
                            "time": null,
                            "xf": null,
                            "kcm": null
                        }
                    ],
                    "flag": null,
                    "dgFlag": "（无）",
                    "ywdgFlag": "（无）",
                    "rlFlag": "20242126,杜昊滢（无）",
                    "xkkzm": "体育"
                }
            ],
            "courseCalendarList": null
        }
    ]
};